# Generated by Django 3.0.6 on 2020-05-29 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('carrinho', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrinhos', to='usuario.Cliente'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produto_carrinho',
            field=models.ManyToManyField(to='produto.ProdutoCarrinho'),
        ),
    ]
