# Generated by Django 3.0.6 on 2020-05-29 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=55)),
                ('imagem', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'marca',
            },
        ),
    ]
