# Generated by Django 3.0.6 on 2020-05-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='imagem',
            field=models.ImageField(upload_to='marcas/'),
        ),
    ]
