# Generated by Django 3.0.6 on 2020-06-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=50, unique=True)),
                ('ano', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'veiculo',
            },
        ),
    ]
