# Generated by Django 3.0.6 on 2020-05-29 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='veiculo',
            table='veiculo',
        ),
    ]
