# Generated by Django 3.0.6 on 2020-05-29 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('', ''), ('', ''), ('', '')], max_length=100)),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='carrinho.Carrinho')),
            ],
        ),
    ]
