# Generated by Django 3.0.6 on 2020-06-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedido", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("elaborando_pedido", "Elaborando Pedido"),
                    ("entregando", "Entregando"),
                    ("entregue", "Entregue"),
                ],
                default="pendente",
                max_length=100,
            ),
        ),
    ]
