version: '3'

services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:10.12-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-emarket}
      - POSTGRES_USER=${POSTGRES_USER:-emarketuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-emarketpassword}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    entrypoint: ./docker/entrypoint.web.sh
    env_file:
      - ../.env
    expose:
      - "8000"
    depends_on:
      - db
      - redis
  celery:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    entrypoint: ./docker/entrypoint.celery.sh
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis://redis:6379}
    depends_on:
      - redis
  nginx:
    image: nginx:1.19.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
