version: '3'

services:
  db:
    image: postgres:10.12-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-emarket}
      - POSTGRES_USER=${POSTGRES_USER:-emarketuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-emarketpassword}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      - db
